# Generated by Django 5.2.7 on 2025-11-10 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('name', models.CharField(choices=[('bug', 'Błąd'), ('feature_request', 'Prośba o nową funkcję'), ('account', 'Problem z kontem'), ('payment', 'Problem z płatnością'), ('other', 'Inne')], max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kategoria ticketu',
                'verbose_name_plural': 'Kategorie ticketów',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tytuł')),
                ('description', models.TextField(verbose_name='Opis problemu')),
                ('status', models.CharField(choices=[('open', 'Otwarty'), ('in_progress', 'W trakcie rozpatrywania'), ('resolved', 'Rozwiązany'), ('closed', 'Zamknięty')], default='open', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Niski'), ('medium', 'Średni'), ('high', 'Wysoki'), ('critical', 'Krytyczny')], default='medium', max_length=20, verbose_name='Priorytet')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Data rozwiązania')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Przypisane do')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.ticketcategory', verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickety',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Zawartość')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('is_staff_comment', models.BooleanField(default=False, verbose_name='Komentarz personelu')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_comments', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Komentarz do ticketu',
                'verbose_name_plural': 'Komentarze do ticketów',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['user', 'status'], name='tickets_tic_user_id_ee01b8_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', '-created_at'], name='tickets_tic_status_15eec8_idx'),
        ),
    ]
