# Generated by Django 5.0 on 2025-12-07 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_options_alter_ticketcategory_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ticket',
            new_name='tickets_user_id_88df9d_idx',
            old_name='tickets_tic_user_id_ee01b8_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='tickets_status_f67985_idx',
            old_name='tickets_tic_status_15eec8_idx',
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='tickets',
        ),
        migrations.AlterModelTable(
            name='ticketcomment',
            table='ticket_comments',
        ),
    ]
