# Generated by Django 5.0 on 2025-12-07 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_rename_tickets_tic_user_id_ee01b8_idx_tickets_user_id_88df9d_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ticketcategory',
            table='ticket_categories',
        ),
    ]
