# Generated by Django 5.2.7 on 2025-10-31 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('roi', 'ROI'), ('yield', 'Yield'), ('loss', 'Loss amount'), ('streak_loss', 'Consecutive losses'), ('custom', 'Custom')], default='yield', max_length=20, verbose_name='Rule Type')),
                ('metric', models.CharField(help_text="Metric to evaluate, e.g., 'roi', 'yield'", max_length=50, verbose_name='Metric')),
                ('comparator', models.CharField(choices=[('lt', 'Less than'), ('lte', 'Less or equal'), ('gt', 'Greater than'), ('gte', 'Greater or equal'), ('eq', 'Equal')], default='lt', max_length=10, verbose_name='Comparator')),
                ('threshold_value', models.DecimalField(decimal_places=4, help_text='Example: ROI -0.1000 for -10%. Loss 500.00 etc.', max_digits=12, verbose_name='Threshold')),
                ('window_days', models.PositiveIntegerField(default=30, verbose_name='Window (days)')),
                ('message', models.CharField(help_text='Message to include in the alert notification.', max_length=255, verbose_name='Alert Message')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='Last triggered at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Alert Rule',
                'verbose_name_plural': 'Alert Rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Query Name')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('statuses', models.JSONField(blank=True, default=list, help_text="e.g. ['won','lost','in_progress']")),
                ('coupon_type', models.CharField(blank=True, choices=[('SOLO', 'Solo'), ('AKO', 'Accumulator'), ('SYSTEM', 'System')], max_length=10, null=True)),
                ('query', models.JSONField(blank=True, help_text='(Deprecated) Use QueryGroup/QueryCondition instead.', null=True)),
                ('group_by', models.JSONField(blank=True, default=list, help_text="Fields to group by, e.g. ['bookmaker', 'status']")),
                ('sort_by', models.JSONField(blank=True, default=list, help_text="Fields to sort by, e.g. ['-created_at', 'bookmaker']")),
                ('metrics', models.JSONField(blank=True, default=list, help_text="Metrics to calculate, e.g. ['total_stake', 'total_return']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analytics Query',
                'verbose_name_plural': 'Analytics Queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsQueryCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(help_text='eg. coupon_type', max_length=255)),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Not Equals'), ('contains', 'Contains'), ('not_contains', 'Not Contains'), ('gt', 'Greater Than'), ('gte', 'Greater Than or Equal'), ('lt', 'Less Than'), ('lte', 'Less Than or Equal'), ('in', 'In'), ('not_in', 'Not In')], max_length=20)),
                ('value', models.JSONField(default=list, help_text='Value or value list')),
                ('negate', models.BooleanField(default=False, help_text='Negates whole condition')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Query Condition',
                'verbose_name_plural': 'Query Conditions',
                'ordering': ['group', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsQueryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('AND', 'AND'), ('OR', 'OR')], default='AND', max_length=3, verbose_name='Operator')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of this group within its parent group.')),
            ],
            options={
                'verbose_name': 'Analytics Query Group',
                'verbose_name_plural': 'Analytics Query Groups',
                'ordering': ['analytics_query', 'parent_id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly'), ('CUSTOM', 'Custom')], default='DAILY', max_length=10, verbose_name='Frequency')),
                ('schedule_payload', models.JSONField(blank=True, help_text='Payload for scheduling the report, e.g., cron expressions.', null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='Next Run Time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('delivery_method', models.CharField(choices=[('email', 'Email'), ('dashboard', 'Dashboard'), ('sms', 'SMS'), ('telegram', 'Telegram')], default='telegram', max_length=20, verbose_name='Delivery Method')),
                ('delivery_methods', models.JSONField(blank=True, default=list, help_text="Methods to deliver the report, e.g., ['email', 'dashboard']")),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
