# Generated by Django 5.2.7 on 2025-10-31 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupon_analytics', '0001_initial'),
        ('coupons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='analyticsquery',
            name='bookmaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_queries', to='coupons.bookmaker', verbose_name='Bookmaker'),
        ),
        migrations.AddField(
            model_name='analyticsquery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_queries', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='analytics_query',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_rules', to='coupon_analytics.analyticsquery', verbose_name='Analytics Query'),
        ),
        migrations.AddField(
            model_name='analyticsquerygroup',
            name='analytics_query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_groups', to='coupon_analytics.analyticsquery', verbose_name='Analytics Query this group belongs to'),
        ),
        migrations.AddField(
            model_name='analyticsquerygroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='coupon_analytics.analyticsquerygroup', verbose_name='Parent Group'),
        ),
        migrations.AddField(
            model_name='analyticsquerycondition',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='coupon_analytics.analyticsquerygroup'),
        ),
        migrations.AddField(
            model_name='report',
            name='query',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='coupon_analytics.analyticsquery', verbose_name='Analytics Query'),
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
