# Generated by Django 5.2.7 on 2025-11-07 15:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_analytics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YieldAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('week', 'Week'), ('month', 'Month'), ('year', 'Year')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('yield_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yield_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coupon_yield_alert',
                'ordering': ['-period_start'],
                'unique_together': {('user', 'period', 'period_start')},
            },
        ),
    ]
