# Generated by Django 5.2.7 on 2025-11-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_analytics', '0003_yieldalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='yieldalert',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
