# Generated by Django 5.0 on 2025-11-26 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_analytics', '0006_delete_yieldalert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Conservative', 'Aggressive', 'Flat Stake'", max_length=100, verbose_name='Strategy Name')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the strategy', null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betting_strategies', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Strategy',
                'verbose_name_plural': 'User Strategies',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='coupon_anal_user_id_790a45_idx')],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
