# Generated by Django 5.0 on 2025-12-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_analytics', '0007_userstrategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Enable/disable report generation', verbose_name='Is Active'),
        ),
    ]
