# Generated by Django 5.0 on 2025-12-07 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_analytics', '0008_report_is_active'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userstrategy',
            new_name='analytics_u_user_id_908e4e_idx',
            old_name='coupon_anal_user_id_790a45_idx',
        ),
        migrations.AlterModelTable(
            name='alertevent',
            table='analytics_alert_event',
        ),
        migrations.AlterModelTable(
            name='alertrule',
            table='analytics_alert_rule',
        ),
        migrations.AlterModelTable(
            name='analyticsquerycondition',
            table='analytics_query_condition',
        ),
        migrations.AlterModelTable(
            name='report',
            table='analytics_report',
        ),
        migrations.AlterModelTable(
            name='userstrategy',
            table='analytics_user_strategy',
        ),
    ]
