# Generated by Django 5.0 on 2025-12-07 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_analytics', '0009_rename_coupon_anal_user_id_790a45_idx_analytics_u_user_id_908e4e_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='analyticsquery',
            table='analytics_query',
        ),
        migrations.AlterModelTable(
            name='analyticsquerygroup',
            table='analytics_query_group',
        ),
    ]
