export const API_BASE_URL = (import.meta.env.VITE_API_BASE_URL as string | undefined) ?? 'http://localhost:8000';

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/api/users/login/',
    REGISTER: '/api/users/register/',
    LOGOUT: '/api/users/logout/',
    REFRESH: '/api/users/token/refresh/',
    ME: '/api/users/me/',
    VERIFY_2FA: '/api/users/auth/login/verify-2fa/',
    GOOGLE_LOGIN: '/api/users/auth/google/',
    PASSWORD_RESET_REQUEST: '/api/users/password/reset/',
    PASSWORD_RESET_CONFIRM: '/api/users/password/reset/confirm/',
    PASSWORD_RESET_RESEND: '/api/users/password/reset/resend/',
  },
  SETTINGS: {
    GET: '/api/users/settings/',
    UPDATE: '/api/users/settings/',
    TWO_FACTOR_START: '/api/users/two-factor/start/',
    TWO_FACTOR_VERIFY: '/api/users/two-factor/verify/',
    TELEGRAM_AUTH_CODE: '/api/users/telegram/auth-code/generate/',
    TELEGRAM_CONNECT: '/api/users/telegram/connect/',
  },
  FINANCES: {
    TRANSACTIONS_LIST: '/api/finances/transactions/',
    TRANSACTION_CREATE: '/api/finances/transactions/create/',
    TRANSACTIONS_SUMMARY: '/api/finances/transactions/summary/',
    BOOKMAKERS_LIST: '/api/finances/bookmakers/',
    BOOKMAKER_ACCOUNT_CREATE: '/api/finances/bookmakers/accounts/create/',
    BOOKMAKER_ACCOUNTS_LIST: '/api/finances/bookmakers/accounts/',
    BOOKMAKER_ACCOUNTS_SUMMARY: '/api/finances/bookmakers/accounts/summary/',
  },
  TICKETS: {
    CATEGORIES: '/api/tickets/categories/',
    LIST: '/api/tickets/tickets/',
    CREATE: '/api/tickets/tickets/',
    DETAIL: (id: string) => `/api/tickets/tickets/${id}/`,
    ADD_COMMENT: (id: string) => `/api/tickets/tickets/${id}/add_comment/`,
    COMMENTS: '/api/tickets/comments/',
  },
  STRATEGIES: {
    LIST: '/api/analytics/strategies/',
    CREATE: '/api/analytics/strategies/',
    DETAIL: (id: number) => `/api/analytics/strategies/${id}/`,
    UPDATE: (id: number) => `/api/analytics/strategies/${id}/`,
    DELETE: (id: number) => `/api/analytics/strategies/${id}/`,
    SUMMARY_LIST: '/api/analytics/strategies/summary/',
    SUMMARY_DETAIL: (id: number | string) => `/api/analytics/strategies/${id}/summary/`,
  },
  ANALYTICS: {
    ALERT_RULES: '/api/analytics/alerts/rules/',
    ALERT_RULE_CREATE: '/api/analytics/alerts/rules/',
  },
  COUPONS: {
    LIST: '/api/coupons/coupons/',
    CREATE: '/api/coupons/coupons/',
    BET_TYPES: '/api/coupons/bet-types/',
    DISCIPLINES: '/api/coupons/disciplines/',
    DISCIPLINE_DETAIL: (id: number | string) => `/api/coupons/disciplines/${id}/`,
    FORCE_WIN: (id: number) => `/api/coupons/coupons/${id}/force-win/`,
    BET_SETTLE: (couponId: number, betId: number | string) => `/api/coupons/coupons/${couponId}/bets/${betId}/`,
    SUMMARY: '/api/coupons/summary/',
    BALANCE_TREND: '/api/coupons/balance-trend/',
    MONTHLY_BALANCE_TREND: '/api/coupons/monthly-balance-trend/',
    FILTER_UNIVERSAL: '/api/coupons/filter/universal/',
    FILTER_QUERY_BUILDER: '/api/coupons/filter/query-builder/',
  },
  MONITORING: {
    SYSTEM_METRICS: '/api/monitoring/system-metrics/',
    LOGGED_IN_USERS: '/api/monitoring/logged-in-users/',
  },
};
