# Generated by Django 5.2.7 on 2025-11-03 18:01

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmakerAccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, help_text="An optional alias for the bookmaker account (e.g., 'My STS Account')", max_length=255, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Current balance of the bookmaker account', max_digits=12)),
                ('website', models.URLField(blank=True, help_text='Website URL of the bookmaker', max_length=500, null=True)),
                ('active', models.BooleanField(default=True, help_text='Indicates whether the bookmaker account is active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the bookmaker account was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the bookmaker account was last updated')),
                ('bookmaker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='coupons.bookmaker')),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='coupons.currency', verbose_name='currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmaker_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bookmaker Account',
                'verbose_name_plural': 'Bookmaker Accounts',
                'ordering': ['bookmaker_id', 'alias', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of the transaction', max_digits=12, verbose_name='amount')),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fee associated with the transaction', max_digits=12, verbose_name='fee')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal')], max_length=10, verbose_name='transaction type')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the transaction was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the transaction was last updated', verbose_name='updated at')),
                ('bookmaker_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finances.bookmakeraccountmodel', verbose_name='bookmaker account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'db_table': 'finance_transactions',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='bookmakeraccountmodel',
            index=models.Index(fields=['user', 'active'], name='idx_ba_user_active'),
        ),
        migrations.AddIndex(
            model_name='bookmakeraccountmodel',
            index=models.Index(fields=['user', 'bookmaker', 'alias', 'id'], name='idx_ba_user_book_alias_id'),
        ),
        migrations.AddIndex(
            model_name='bookmakeraccountmodel',
            index=models.Index(fields=['bookmaker'], name='idx_ba_bookmaker'),
        ),
        migrations.AddConstraint(
            model_name='bookmakeraccountmodel',
            constraint=models.UniqueConstraint(fields=('user', 'bookmaker'), name='uniq_user_bookmaker'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'transaction_type'], name='finance_tra_user_id_1ab406_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='finance_tra_created_41f97c_idx'),
        ),
    ]
