# Generated by Django 5.0 on 2025-12-07 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_remove_transaction_fee'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookmakeraccountmodel',
            table='finance_bookmaker_accounts',
        ),
    ]
