# Generated by Django 5.2.7 on 2025-10-31 19:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BetTypeDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Bet Type',
                'verbose_name_plural': 'Bet Types',
            },
        ),
        migrations.CreateModel(
            name='Bookmaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Bookmaker name, e.g., 'STS'", max_length=255, unique=True)),
                ('tax_multiplier', models.DecimalField(decimal_places=2, default=0.88, help_text='Tax multiplier for the bookmaker (e.g., 0.88 for 12% tax)', max_digits=4)),
            ],
            options={
                'verbose_name': 'Bookmaker',
                'verbose_name_plural': 'Bookmakers',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Currency code must be 3 uppercase letters.')])),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'currencies',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Short, unique code (e.g., SOC, BASK, TEN). Stored in UPPERCASE.', max_length=12, unique=True)),
                ('name', models.CharField(help_text='Sport discipline name (e.g., Football / Soccer).', max_length=100, unique=True)),
                ('category', models.CharField(choices=[('team_sport', 'Team sport'), ('racket_sport', 'Racket sport'), ('combat_sport', 'Combat sport'), ('precision_sport', 'Precision sport'), ('motorsport', 'Motorsport'), ('endurance', 'Endurance'), ('cue_sport', 'Cue sport'), ('esport', 'Esport'), ('other', 'Other')], default='team_sport', max_length=32)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the strategy, e.g. 'Flat Stake', 'Progressive', 'Martingale'", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='', help_text="Event name (e.g., 'Barcelona vs Real Madrid')", max_length=255)),
                ('line', models.CharField(default='', help_text="Bet line/selection (e.g., '1', 'X', '2', 'OVER 2.5', 'UNDER 2.5')", max_length=50)),
                ('odds', models.DecimalField(decimal_places=2, help_text='Odds for the bet (must be > 1.00)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))])),
                ('result', models.CharField(blank=True, choices=[('win', 'Win'), ('lost', 'Lost'), ('canceled', 'Canceled(settled @1.00)')], help_text='Result of the bet', max_length=10, null=True)),
                ('bet_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupons.bettypedict')),
            ],
            options={
                'verbose_name': 'Bet',
                'verbose_name_plural': 'Bets',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon_type', models.CharField(choices=[('SOLO', 'Solo'), ('AKO', 'Accumulator'), ('SYSTEM', 'System')], db_index=True, default='SOLO', max_length=10)),
                ('bet_stake', models.DecimalField(decimal_places=2, help_text='Total stake amount for the coupon', max_digits=10)),
                ('multiplier', models.DecimalField(decimal_places=2, help_text='Odds multiplier for the coupon', max_digits=10)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('won', 'Won'), ('lost', 'Lost'), ('canceled', 'Canceled')], default='in_progress', help_text='Current status of the coupon', max_length=15)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Current balance of the coupon', max_digits=10)),
                ('bookmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='coupons.bookmaker')),
            ],
        ),
    ]
