# Generated by Django 5.2.7 on 2025-10-27 10:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Bookmaker name, e.g., 'STS'", max_length=255, unique=True)),
                ('tax_multiplier', models.DecimalField(decimal_places=2, default=0.88, help_text='Tax multiplier for the bookmaker (e.g., 0.88 for 12% tax))', max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the strategy, e.g. 'Flat Stake', 'Progressive', 'Martingale'", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon_type', models.CharField(choices=[('SOLO', 'Solo'), ('AKO', 'Accumulator'), ('SYSTEM', 'System')], default='SOLO', help_text='Type of the coupon: SOLO or COMBO', max_length=10)),
                ('bet_stake', models.DecimalField(decimal_places=2, help_text='Total stake amount for the coupon', max_digits=10)),
                ('multiplier', models.DecimalField(decimal_places=2, help_text='Odds multiplier for the coupon', max_digits=10)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('won', 'Won'), ('lost', 'Lost'), ('canceled', 'Canceled')], default='in_progress', help_text='Current status of the coupon', max_length=15)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Current balance of the coupon', max_digits=10)),
                ('bookmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='coupons.bookmaker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL)),
                ('strategy', models.ForeignKey(blank=True, help_text='The strategy that this coupon should be applied to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', related_query_name='coupon', to='coupons.strategy')),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(help_text="Name of the event, e.g., 'Team A vs Team B'", max_length=255)),
                ('bet_type', models.CharField(help_text="Type of the bet, e.g. 'Full Time', 'Over/Under', BTTS", max_length=255)),
                ('odds', models.DecimalField(decimal_places=2, help_text='Odds for the bet', max_digits=10)),
                ('result', models.CharField(blank=True, choices=[('win', 'Win'), ('lost', 'Lost'), ('canceled', 'Canceled(settled @1.00)')], help_text='Result of the bet', max_length=10, null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet', related_query_name='coupon this bet belongs to', to='coupons.coupon')),
            ],
            options={
                'verbose_name': 'Bet',
                'verbose_name_plural': 'Bets',
            },
        ),
    ]
