# Generated by Django 5.2.7 on 2025-10-31 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bet',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='coupons.coupon'),
        ),
        migrations.AddConstraint(
            model_name='discipline',
            constraint=models.CheckConstraint(check=models.Q(('code', ''), _negated=True), name='sport_code_not_blank'),
        ),
        migrations.AddField(
            model_name='bet',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupons.discipline'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='strategy',
            field=models.ForeignKey(blank=True, help_text='The strategy that this coupon should be applied to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', related_query_name='coupon', to='coupons.strategy'),
        ),
    ]
