# Generated by Django 5.2.7 on 2025-11-04 14:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(help_text='Name of the event (e.g., Team A vs Team B)', max_length=200, verbose_name='Event name')),
                ('start_time', models.DateTimeField(help_text='Scheduled start time of the event', verbose_name='Start time')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='coupons.discipline', verbose_name='Discipline')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ('-start_time',),
            },
        ),
        migrations.AddField(
            model_name='bet',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Related event for this bet', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bets', to='coupons.event'),
        ),
    ]
