# Generated by Django 5.2.7 on 2025-11-04 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_event_bet_event'),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='bookmaker',
        ),
        migrations.AddField(
            model_name='coupon',
            name='bookmaker_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to='finances.bookmakeraccountmodel'),
        ),
    ]
