# Generated by Django 5.2.7 on 2025-11-04 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_remove_coupon_bookmaker_coupon_bookmaker_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Related event for this bet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bets', to='coupons.event'),
        ),
    ]
