# Generated by Django 5.2.7 on 2025-11-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_alter_bet_coupon_cascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='away_team',
            field=models.CharField(blank=True, help_text='Name of the away team', max_length=200, null=True, verbose_name='Away team'),
        ),
        migrations.AddField(
            model_name='event',
            name='home_team',
            field=models.CharField(blank=True, help_text='Name of the home team', max_length=200, null=True, verbose_name='Home team'),
        ),
    ]
