# Generated by Django 5.0 on 2025-11-27 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_analytics', '0007_userstrategy'),
        ('coupons', '0007_event_away_team_event_home_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='strategy',
            field=models.ForeignKey(blank=True, help_text='User-defined strategy associated with this coupon.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', related_query_name='coupon', to='coupon_analytics.userstrategy'),
        ),
        migrations.DeleteModel(
            name='Strategy',
        ),
    ]
