# Generated by Django 5.0 on 2025-11-27 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0008_alter_coupon_strategy_delete_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='bettypedict',
            name='discipline',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='bet_types', to='coupons.discipline'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='bettypedict',
            unique_together={('code', 'discipline')},
        ),
    ]
