# Generated by Django 5.0 on 2025-11-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0009_bettypedict_discipline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bettypedict',
            name='code',
            field=models.CharField(max_length=32),
        ),
    ]
