# Generated by Django 5.0 on 2025-12-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0010_alter_bettypedict_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bettypedict',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bettypedict',
            name='disciplines',
            field=models.ManyToManyField(related_name='bet_types', to='coupons.discipline'),
        ),
        migrations.AlterField(
            model_name='bettypedict',
            name='code',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.RemoveField(
            model_name='bettypedict',
            name='discipline',
        ),
    ]
