# Generated by Django 5.0 on 2025-12-07 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0011_change_bet_type_dict_to_many_to_many'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bet',
            table='bets',
        ),
        migrations.AlterModelTable(
            name='bettypedict',
            table='bet_type_dict',
        ),
        migrations.AlterModelTable(
            name='bookmaker',
            table='bookmakers',
        ),
        migrations.AlterModelTable(
            name='coupon',
            table='coupons',
        ),
        migrations.AlterModelTable(
            name='discipline',
            table='disciplines',
        ),
        migrations.AlterModelTable(
            name='event',
            table='events',
        ),
    ]
