# Generated by Django 5.2.7 on 2025-11-05 16:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_telegramuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_auth_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram Auth Code',
                'verbose_name_plural': 'Telegram Auth Codes',
                'db_table': 'users_telegram_auth_code',
            },
        ),
    ]
