# Generated by Django 5.2.7 on 2025-11-09 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usersettings_yield_month_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='yield_month_threshold',
            field=models.DecimalField(decimal_places=2, default=-5.0, help_text='Próg % dla miesięcznego YIELD.', max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='yield_week_threshold',
            field=models.DecimalField(decimal_places=2, default=-5.0, help_text='Próg % dla tygodniowego YIELD poniżej którego wysyłamy alert (np. 5.00).', max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='yield_year_threshold',
            field=models.DecimalField(decimal_places=2, default=-5.0, help_text='Próg % dla rocznego YIELD.', max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
