# Generated by Django 5.2.7 on 2025-11-09 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_usersettings_yield_month_threshold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='yield_month_enabled',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='yield_month_threshold',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='yield_week_enabled',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='yield_week_threshold',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='yield_year_enabled',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='yield_year_threshold',
        ),
    ]
