# Generated by Django 5.0 on 2025-11-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_usersettings_yield_month_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='predefined_bet_values',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
