# Generated by Django 5.0 on 2025-11-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0010_alter_bettypedict_code'),
        ('users', '0007_usersettings_predefined_bet_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='favourite_bet_types',
            field=models.ManyToManyField(blank=True, related_name='user_favourite_settings', to='coupons.bettypedict'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='favourite_disciplines',
            field=models.ManyToManyField(blank=True, related_name='user_favourite_settings', to='coupons.discipline'),
        ),
    ]
