# Generated by Django 5.0 on 2025-12-08 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_usersettings_favourite_bet_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='two_factor_method',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='two_factor_secret',
        ),
    ]
