# Generated by Django 5.0 on 2025-12-08 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_otp_email_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='notification_gate_ref',
        ),
    ]
