# Generated by Django 5.0 on 2025-12-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_notification_gate_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='budget_exceeded_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
